# Generated by Django 3.0 on 2021-02-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_room_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
    ]
