# Generated by Django 3.0 on 2021-03-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20210227_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
